config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  
  resource :dashboard, only: [:show]
  resources :games, only: [:index, :new, :create, :update, :show, :destroy] do
    resources :pieces, only: [:create, :show, :update]
  end
  resources :games do
    member do
        put :concede
      end
  end

end

app/models/game.rb
class Game < ApplicationRecord
  scope :available, -> { where(black_id: nil, game_over: false) }
  belongs_to :user, required: false
  belongs_to :white_player, class_name: 'User', foreign_key: 'white_id', optional: true
  belongs_to :black_player, class_name: 'User', foreign_key: 'black_id', optional: true
  has_many :pieces
  after_create :populate_board!
  after_create :set_game_defaults

  def set_game_defaults
      update_attributes(turn: 1, game_over: false)
  end
  
  def populate_board!
    # WHITE PIECES

    (1..8).each do |f|
      Pawn.create(x_pos: f, y_pos: 7, game_id: id, player_id: white_id, color: "white")
    end

    [1,8].each do |f|
    	Rook.create(x_pos: f, y_pos: 8, game_id: id, player_id: white_id, color: "white")
    end

    [2,7].each do |f|
    	Knight.create(x_pos: f, y_pos: 8, game_id: id, player_id: white_id, color: "white")
    end

    [3,6].each do |f|
    	Bishop.create(x_pos: f, y_pos: 8, game_id: id, player_id: white_id, color: "white")
    end

     Queen.create(x_pos: 4, y_pos: 8, game_id: id, player_id: white_id, color: "white")   


     King.create(x_pos: 5, y_pos: 8, game_id: id, player_id: white_id, color: "white")




    # BLACK PIECES 

    (1..8).each do |f|
      Pawn.create(x_pos: f, y_pos: 2, game_id: id, player_id: black_id, color: "black")
    end

    [1,8].each do |f|
    	Rook.create(x_pos: f, y_pos: 1, game_id: id, player_id: black_id, color: "black")
    end

    [2,7].each do |f|
    	Knight.create(x_pos: f, y_pos: 1, game_id: id, player_id: black_id, color: "black")
    end

    [3,6].each do |f|
    	Bishop.create(x_pos: f, y_pos: 1, game_id: id, player_id: black_id, color: "black")
    end

    Queen.create(x_pos: 4, y_pos: 1, game_id: id, player_id: black_id, color: "black")
  
    King.create(x_pos: 5, y_pos: 1, game_id: id, player_id: black_id, color: "black")



  end

  def stalemate(player_id)
    king = game.pieces.find_by(type: 'King', player_id: player_id)
    player_pieces = game.pieces.where(player_id: player_id)
    (1..8).each do |goal_x|
      (1..8).each do |goal_y|
        if player_pieces.invalid?(goal_x, goal_y) == false && king.check?(goal_x, goal_y) == true
          return true
        end
      end
    end
  end


  def checkmate?(player_id)
    king = game.pieces.find_by(type: 'King', player_id: player_id)
    if king.check? && stalemate?(player_id)
      return true
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @avail_games = Game.available
  end
  
  def new
    @game = Game.new
  end

  def create 
    @game = Game.create(game_params)
    redirect_to game_path(@game)
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(black_id: current_user.id)
    redirect_to game_path(@game)
  end

  def concede
    @game = Game.find(params[:id])
    if current_user.id == @game.white_id
      @game.update_attributes(winner: @game.black_id)
    else
      @game.update_attributes(winner: @game.white_id)
    end
    @game.update_attributes(game_over: true)
    redirect_to games_path
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    Game.destroy(params[:id])
    redirect_to root_path
  end

  def set_tie
    @game = Game.find(params[:id])
    if @game.stalemate(current_user.id)
      @game.update_attributes(game_over: true)
      white_player.update_attributes(num_ties: white_player.num_ties + 1)
      black_player.update_attributes(num_ties: black_player.num_ties + 1)
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :white_id, :black_id, :user_id, :game_over, :winner)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="devise_wrapper" style="height:auto;">
  <%# AVAILABLE GAMES (BLACK_ID = NIL) %>
  <div class="available">
    <div class="browse_bar">
      <h1 class="browse">Browse Available Games</h1>
    </div>

    <% if @avail_games.blank? %>
      <div class="col-10 offset-1" style="margin-top:15%; margin-bottom:10%;">
        <div class="browse mt-auto mb-auto"><h1>No Games Available :-(</h1></div>
      </div>
      <br />
    <% end %>

    <div class="row justify-content-center">
      <% @avail_games.each do |game| %>
        <div class="devise-box col-12 col-sm-3 ml-4 mr-4">
          <h5>
            <%= game.name %>
          </h5>
          <i class="fa fa-chess-board board mb-3"></i>
          <h6>
            Opponent: <%= game.white_player.username %>
          </h6>
            <%= simple_form_for game, :method => :put do |f| %>
              <%= f.input :black_id, :as => :hidden, :input_html => { :value => current_user.id } %>
              <%= f.submit 'Join Game', class: 'btn-primary btn-g pt-1 pb-1 mt-1' %>
            <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-12 text-center">
      <%= link_to 'Create New Game', new_game_path, class: 'btn btn-d btn-primary mt-3 mb-1', style: 'width:auto;' %>
    </div>
  </div>
  <br />
</div>
<div class="devise_wrapper" style="height:100%;">
</div>

app/views/games/new.html.erb
<div class="devise_wrapper row" style="height:100%;">
  <br />
  <div class="devise-box col-10 offset-1 col-sm-6 offset-sm-3 text-center" style="height:auto;">
    <h1 class="browse text-center mt-2">Create New Game</h1>
    <hr />
    <h4>Game Title</h4>
    <%= simple_form_for @game do |f| %>
      <%= f.input :name, label: false %>
      <%= f.hidden_field :white_id, value: current_user.id %>
      <%= f.submit "Create", class: 'btn btn-d btn-primary mt-3' %>
    <% end %>
  </div>
  <div class="devise-box-alt mt-0 col-10 offset-1 col-sm-6 offset-sm-3 text-center">
    <h4 class="mt-4"> Did you know? </h4>
    <hr class="f_hr" />
    <p class="facts col-12 text-center"><%= Facts.give_fact %><p>
  </div>
</div>

app/views/games/show.html.erb
<p>
	white_id: <%= @game.white_id%>
	<br />
	white_player.id: <%= @game.white_player.id%>
	<br />
	black_id: <%= @game.black_id%>
	<br />
	black_player.id: <%= @game.black_player.id%>
	<br />
	current_user: <%= current_user.id%>
	<br />
	current_user.username: <%= current_user.username%>
	<br />
</p>

<div class="game_bar row text-center pt-4">
	<div class="col-12 col-sm-3 text-left mb-1">
		<h5 class="game_title"><%= @game.name %></h5>
	</div>
	<div class="col-12 col-sm-4 offset-sm-1"> 
		<h5 class="game_labels">White Player:</h5> <%= @game.white_player.username %>
	</div>
	<div class="col-12 col-sm-4">
		<h5 class="game_labels">Red Player:</h5>
		<% if @game.black_player.present? %>
			<%= @game.black_player&.username %>
		<% else %>
			Waiting for opponent...
		<% end %>
	</div> 
</div>

<div id="show_game">
	<div class="col-12 turn text-center mt-0 move">
		<% if @game.turn.odd? && @game.white_player == current_user || @game.turn.even? && @game.black_player == current_user %>
			It's Your Move
		<% else %>
			Waiting for Opponent's Move
		<% end %>
		&nbsp <%= link_to 'Forfeit Game', concede_game_path(@game), class: 'button btn btn-lg btn-danger forfeit mt-4 mb-4', user_id: current_user, method: :put, data: { confirm: 'Are you sure you want to forfeit? (It will count as a loss)' } %>
	</div>
	<div class="chessboard">
		<% (1..8).each do |y| %>
			<div class="row">
				<% (1..8).each do |x| %>
					<div class="<%= (x + y).odd? ? 'black' : 'white' %> space" data-x="<%= x %>" data-y="<%= y %>" >
						<% @game.pieces.where(x_pos: x, y_pos: y).each do |piece| %>
							<% if piece.player_id == @game.white_id %>
								<span class="<%= piece.render %> white piece wp" data-id= "<$= piece.id %>" data-update-url="<%= game_piece_path(@game, piece) %>" id="piece"></span>
							<% else %>
								<span class="<%= piece.render %> red piece" data-id= "<%= piece.id %>" data-update-url="<%= game_piece_path(@game, piece) %>" id="piece"></span>
							<% end %>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

<% if @game.white_player.username == current_user.username %>
	<script>
		$(".red").click (function() {
		alert("Not Your Piece!");
		});
	</script>

	<% else %>

	<script>
		$(".wp").click (function() {
		alert("Not Your Piece!");
		});
	</script>

<% end %>

<script>

<% if @game.turn.odd? %>
	$(document).ready(function () {

		$(".piece").draggable({
			containment: '.chessboard',
			revert: false,
			opacity: .4,
			create: function(){$(this).data('position',$(this).position())},
			cursorAt:{left:15},
			start:function(){$(this).stop(true,true)}
		});
		$(".space").droppable({
			snap: '.space',
			drop:function(event, ui){
				var confirmation = confirm("are you sure you want to remove the item?");
				if (confirmation) {
				snapToMiddle(ui.draggable,$(this));
				var x = $(this).attr('data-x')
				var y = $(this).attr('data-y')
				$.ajax({
					type: 'PUT',
						url: ui.draggable.data('update-url'),
						dataType: 'json',
						data: { piece: { x_pos: x, y_pos: y } },
						});
						} else {
							$(".piece").draggable({
								revert: true,
						});
						}
						window.location.href = window.location.href;
					}
				});
			});
	function snapToMiddle(dragger, target){
			var topMove = target.position().top - dragger.data('position').top + (target.outerHeight(true) - dragger.outerHeight(true)) / 40;
			var leftMove= target.position().left - dragger.data('position').left + (target.outerWidth(true) - dragger.outerWidth(true)) / 2;
			dragger.animate({top:topMove,left:leftMove},{duration:600,easing:'easeOutBack'});
	}

	</script>
<% end %>