config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static#index'
  
  resource :dashboard, only: [:show]
  resources :games, only: [:index, :new, :create, :update, :show, :destroy] do
    resources :pieces, only: [:create, :show, :update]
  end
  resources :games do
    member do
        put :concede
      end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess with Mates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-lg fa-chess-knight logo", style="color: rgba(117, 49, 40, 0.91);"></i> 
        <div class="title ml-1">
          Chess <span class="with" style="font-size:18px;">with</span> Mates
        </div>
      <% end %>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Play Now
      </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Browse Available Games', games_path, class: 'dropdown-item' %>
          <%= link_to 'Create New Game', new_game_path, class: 'dropdown-item' %>
        </div>
      <!-- </li>
        <li class="nav-item active">
          <%= link_to 'Join Game', games_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Create Game', new_game_path, class: 'nav-link' %>
        </li> ! -->
      </ul>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %> 

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <div class="clear"></div>
  <div class="footer_wrapper">
    <footer class="footer">        
    <br />
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-4 text-center mb-3">
            <h5>Quick Links</h5>
            <hr class="f_hr mt-0 mb-2" />
            <%= link_to 'Join Game', games_path %>
            <br />
            <%= link_to 'Create Game', new_game_path %>
            <br />
            <%= link_to 'My Dashboard', '#' %>
          </div>
          <div class="col-12 col-sm-4 text-center mb-3">
            <h5>About</h5>
            <hr class="f_hr mt-0 mb-2" />
            <%= link_to 'Meet the Team', '#' %>
            <br />
            <%= link_to 'Privacy Policy', '#' %>
          </div>
          <div class="col-12 col-sm-4 text-center repo">
            <h5>Repository</h5>
            <hr class="f_hr mt-0 mb-2" />
            <%= link_to 'https://github.com/UCF-AUGUST2019/ChessApp' do %>
              <i class="fab fa-lg fa-github mt-1"></i>&nbsp GitHub
            <% end %>
          </div>
        </div>
      </div>
    </footer>
  </div>

    <div class="clear"></div>

  </div>          
  </body>

</html>